[project]
name = "hyuga-hyground"
version = "0.1.0"
description = "(Yet Another (Yet Another)) Hy Language Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hy>=1.1.0",
    "hyrule>=1.0.0",
    "pytest>=8.4.0",
    "toolz>=1.0.0",
]
